### PR TITLE
Add test-e2e-ambient for 1.22 release

### PR DESCRIPTION
**Pull request by paulwilljones**
⚠️ Only merge after https://github.com/cert-manager/istio-csr/pull/336

### CODE REVIEW

**Comment by inteon** [comment]
@SgtCoDFish do we still have to merge this? Also, is the `test-e2e-pure-runtime` target being called anywhere already?
A cleaner solution might be to bundle these targets in the istio-csr repo under `test-e2e` and just keep calling a single Makefile target here.

**Comment by SgtCoDFish** [comment]
Yeah this needs to merge I think. I don't think it's the end of the world that it hasn't gone in yet though!

I'm open to reworking how these tests are called down the road as long as each e2e test can still easily be run individually!

**Comment by SgtCoDFish** [comment]
Oh, maybe this should run as a separate test rather than being tacked onto an existing one 🤔  I'll sort that out

**Comment by SgtCoDFish** [comment]
@inteon I've changed this to add pure runtime tests + ambient tests as separate targets 👍

**Review by inteon — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
