### PR TITLE
Apply upstream changes

### PR DESCRIPTION
**Pull request by inteon**
Update prow yaml based on upstream (result of manually comparing yaml with upstream).
see https://github.com/kubernetes/test-infra/tree/master/config/prow/cluster

### CODE REVIEW

**Comment by inteon** [comment]
I applied these changes to the cluster & everything is still working.

**Comment by maelvls** [comment]
What do you mean by upstream? I am a bit confused by where these changes come from

**Comment by inteon** [comment]
> What do you mean by upstream? I am a bit confused by where these changes come from

I got the changes from here: https://github.com/kubernetes/test-infra/tree/master/config/prow/cluster

**Review by SgtCoDFish — APPROVED** [review]
/lgtm
/approve

Obviously I can't really review the diff on the CRD given the size. I think we should proceed and look later if there's a problem 😁

**Pull request merged**
